apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: coffee

spec: 
  replicas: 2 
  selector: 
   matchLabels:
     app: coffee

  template: 
   metadata:
      name: tmp-coffee 
      labels:
        app: coffee
   spec: 
     containers:
      - name: c2 
        image: abhipraydh96/coffee 
        ports:
        - containerPort: 80
---
apiVersion: v1 
kind: Service 
metadata:
  name: svc-cofee
spec:
  selector:
    app: coffee
  ports:
   - protocol: "TCP"
     port: 80
     targetPort: 80
  type: NodePort
